version: '3.2'

services:
        mysql:
                image: mysql:latest
                container_name: mysql
                ports:
                        - 3306:3306
                volumes:
                        - /home/sanglv12/db:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=${DB_NAME}
                        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        django:
                image: django:1.0
                container_name: app
                ports:
                        - 8000:8000
                depends_on:
                        - mysql
